{% set name = "GalSim" %}
{% set version = "2.2.2" %}
{% set sha256 = "a665606eabc52fe2631c0c3d5f7ac3fc66200272784a9d2a81822f2434762d4d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Galsim-Developers/galsim/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-remove-run-install-checks.patch

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - scons

  host:
    - python
    - numpy
    - pybind11 >=2.2
    - fftw >=3.3
    - eigen >=3.3

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - future >=0.15
    - astropy >=2.0
    - pybind11 >=2.2
    - fftw >=3.3
    - eigen >=3.3
    - lsstdesc.coord >=1.0.5

test:
  imports:
    - galsim

about:
  home: https://github.com/GalSim-developers/GalSim
  license: BSD
  license_file: LICENSE
  summary: The modular galaxy image simulation toolkit
  description: |
    GalSim is open-source software for simulating images of astronomical objects
    (stars, galaxies) in a variety of ways. The bulk of the calculations are
    carried out in C++, and the user interface is in python. In addition, the
    code can operate directly on "config" files, for those users who prefer not
    to work in python. (http://adsabs.harvard.edu/abs/2015A%26C....10..121R)
  doc_url: https://github.com/GalSim-developers/GalSim/wiki
  dev_url: https://github.com/GalSim-developers/GalSim

extra:
  recipe-maintainers:
    - beckermr
