{% set name = "GalSim" %}
{% set version = "2.5.0" %}
{% set sha256 = "31d233244926d43734477e8769656db83541bbfaa83a6303172f2d58886fe39f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Galsim-Developers/galsim/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]

  host:
    - python
    - numpy
    - pybind11 >=2.2
    - fftw
    - eigen >=3.3
    - pip

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - astropy >=2.0
    - pybind11 >=2.2
    - eigen >=3.3
    - lsstdesc.coord >=1.0.5
    - scipy

test:
  imports:
    - galsim
  commands:
    - ls -lah $PREFIX/lib/libgalsim*
    - ldd $PREFIX/lib/libgalsim.so  # [linux]
    - otool -L $PREFIX/lib/libgalsim.dylib  # [osx]
    - test -f $PREFIX/lib/libgalsim${SHLIB_EXT}
    - test -L $PREFIX/lib/libgalsim${SHLIB_EXT}
    - test -f $PREFIX/include/GalSim.h
    - test -d $PREFIX/include/galsim
    - otool -D ${PREFIX}/lib/libgalsim.dylib | tail -n1 | grep "@rpath/libgalsim"  # [osx]

about:
  home: https://github.com/GalSim-developers/GalSim
  license: MIT AND BSD-2-Clause
  license_file: LICENSE
  summary: The modular galaxy image simulation toolkit
  description: |
    GalSim is open-source software for simulating images of astronomical objects
    (stars, galaxies) in a variety of ways. The bulk of the calculations are
    carried out in C++, and the user interface is in python. In addition, the
    code can operate directly on "config" files, for those users who prefer not
    to work in python. (http://adsabs.harvard.edu/abs/2015A%26C....10..121R)
  doc_url: https://github.com/GalSim-developers/GalSim/wiki
  dev_url: https://github.com/GalSim-developers/GalSim

extra:
  recipe-maintainers:
    - beckermr
    - rmjarvis
    - erykoff
