travis:
  secure:
    BINSTAR_TOKEN: kdnhruVQnFSacfn9cPo5qEVfStuoPQ6Yo2/ydJip4uLA8o910j7836js2FfOKSNrEV04oBqVKvFqfMQHERAQ2ndTGX8I6EpgdszGH/S8gHkm7eIVSC2ux5of+gZoi5HxFyWPGnVBaLHqposbG7+zFceZRRXly6IumsEAsQZ4MrSbua5sPaCnVnqKLdM9MTPcf9QIo7D/aMiuNv5H56Ka26kJcifhcB5lDUfq/uoqNrEPaorJIL0Trcls+fBRLGFOJLcnHfi3Q6cu0q24IXYmGQb9Ks6eBkU9TlJcANAp4liXYMmsb+vHlFb6BkFh7B5ljVMNBqxJqZYRkEjdEm91F7afwwkP4QkrEMQBWnSLdhFEhd0ueXACYM1Ua4wfRObbKePJhcrDTyeqce111yP8B+wFerjeTbbwVTjZdbHIKSxxPZoGq4oo40Oq55gjvK0xcIYTPkirboa+qpmh91gr7JNiWyWx+kb9Q6SAmYJpwbOA87r3k1/+cXDAbY9ToMNiSgG5XvPgoguR482g/+yuGgd6vlvefvQkxdZ1jp/AFTCH7G0JKonZ70+/m1uVv+0VrcOlw3aDMSHy55VQ8RM6k2+nxjIfiZTsZITaQBKgD5SnHBLzoXQC8QNHXXiix9r5XpEOlgoqUOabLQadSE+e2U6xwy7KYdpx8uNrrfI8foA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
